package es.unileon.happycow.gui.panels.admin;

import es.unileon.happycow.controller.admin.AdminController;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author dorian
 */
public class Administrator extends javax.swing.JPanel {
    private AdminController controller;

    public Administrator(AdminController controller) {
        this.controller = controller;
        initComponents();
    }
    
    public void addTab(String title, JPanel panel){
        tabbs.addTab(title, panel);
        if(controller!=null){
            controller.addTab((InterfaceTabs)panel);
        }
    }
    
    public void setController(AdminController controller){
        this.controller=controller;
        for (Component component : tabbs.getComponents()) {
            controller.addTab((InterfaceTabs)component);
        }
    }

    /**
     * Creates new form Administrator
     */
    public Administrator() {
        this(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbs = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        tabbs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabbsMouseClicked(evt);
            }
        });
        add(tabbs, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tabbsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbsMouseClicked
        controller.changeTab(tabbs.getSelectedIndex());
    }//GEN-LAST:event_tabbsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbs;
    // End of variables declaration//GEN-END:variables
}
