package es.unileon.happycow.gui;

import es.unileon.happycow.controller.ReportController;
import javax.swing.JEditorPane;

/**
 *
 * @author dorian
 */
public class PanelReport extends javax.swing.JPanel {
    
    private ReportController controller;

    /**
     * Creates new form PanelReport
     */
    public PanelReport() {
        this(null);
    }
    
    public PanelReport(ReportController controller) {
        initComponents();
        configureComponents();
        this.controller=controller;
    }

    public void setController(ReportController controller) {
        this.controller = controller;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        buttonPrint = new javax.swing.JButton();
        buttonListFarms = new javax.swing.JButton();
        buttonFarm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        editorPane = new javax.swing.JEditorPane();
        buttonHelp = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setLayout(new java.awt.GridBagLayout());

        buttonPrint.setText("Imprimir");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(buttonPrint, gridBagConstraints);

        buttonListFarms.setText("Volver al listado de granjas");
        buttonListFarms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListFarmsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(buttonListFarms, gridBagConstraints);

        buttonFarm.setText("Volver a la granja");
        buttonFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFarmActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(buttonFarm, gridBagConstraints);

        editorPane.setContentType("text/html"); // NOI18N
        editorPane.setText("<html>\n  <head>\n\n  </head>\n  <body>\n<h1>Titulo formato</h1>\n    <p style=\"margin-top: 0\">\n      BEAAA!!! vamos a trolear un poco por si te da por mirar aquí... Muahahahahaha!!!\n    </p>\n<p>Y cómo coño establezco yo el tamaño de párrafos y páginas?!?!?! :(</p>\n  </body>\n</html>\n");
        editorPane.setMaximumSize(new java.awt.Dimension(700, 2147483647));
        editorPane.setMinimumSize(new java.awt.Dimension(1034, 720));
        editorPane.setName(""); // NOI18N
        jScrollPane1.setViewportView(editorPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jScrollPane1, gridBagConstraints);

        buttonHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help.png"))); // NOI18N
        buttonHelp.setBorderPainted(false);
        buttonHelp.setContentAreaFilled(false);
        buttonHelp.setFocusPainted(false);
        buttonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHelpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(buttonHelp, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void createComponents(){
        
    }
    
    private void configureComponents(){
        buttonHelp.setBorderPainted(false);
        buttonHelp.setContentAreaFilled(false);
        buttonHelp.setFocusPainted(false);
    }
    
    private void addEvents(){
        JFrameApplication.getInstance().getHelp().setHelpOnButton(buttonHelp, "AyudaReporte");
        JFrameApplication.getInstance().getHelp().setHelp(this, "AyudaReporte");
    }
    
    private void addLayout(){
        
    }
    
    public void setReport(String text){
        
    }
    
    public JEditorPane getEditor(){
        return editorPane;
    }
    
    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        controller.print();
    }//GEN-LAST:event_buttonPrintActionPerformed

    private void buttonListFarmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListFarmsActionPerformed
        controller.listFarms();
    }//GEN-LAST:event_buttonListFarmsActionPerformed

    private void buttonFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFarmActionPerformed
        controller.farm();
    }//GEN-LAST:event_buttonFarmActionPerformed

    private void buttonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHelpActionPerformed
        
    }//GEN-LAST:event_buttonHelpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFarm;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JButton buttonListFarms;
    private javax.swing.JButton buttonPrint;
    private javax.swing.JEditorPane editorPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
