package es.unileon.happycow.gui;

import es.unileon.happycow.controller.PasswordController;
import javax.swing.JPasswordField;

/**
 *
 * @author dorian
 */
public class PanelPassword extends javax.swing.JPanel {
    private PasswordController controller;

    /**
     * Creates new form PanelPassword
     */
    public PanelPassword() {
        initComponents();
    }
    
    public void createComponents(){
        
    }
    
    public void configureComponents(){
        
    }
    
    public void addEvents(){
        
    }
    
    public void addLayout(){
        
    }
    
    public void setController(PasswordController controller) {
        this.controller = controller;
    }
    
    public String getOldPassword(){
        return new String(textOldPassword.getPassword());
    }
    
    public String getNewPassword(){
        return new String(textNewPassword.getPassword());
    }
    
    public boolean isPasswordMatch(){
        String firstPass=new String(textNewPassword.getPassword());
        String secondPass=new String(textRenewPassword.getPassword());
        return firstPass.compareTo(secondPass)==0 && firstPass.length()>0;
    }

    public void setMessage(String message) {
        lblMessage.setText(message);
    }
    
    private void clearMessage(){
        lblMessage.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblNewPassword = new javax.swing.JLabel();
        lblRenewPassword = new javax.swing.JLabel();
        lblOldPassword = new javax.swing.JLabel();
        textNewPassword = new javax.swing.JPasswordField();
        textRenewPassword = new javax.swing.JPasswordField();
        textOldPassword = new javax.swing.JPasswordField();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        lblNewPassword.setText("Introduzca la nueva contraseña");
        lblNewPassword.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        add(lblNewPassword, gridBagConstraints);

        lblRenewPassword.setText("Reintroduzca la nueva contraseña");
        lblRenewPassword.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        add(lblRenewPassword, gridBagConstraints);

        lblOldPassword.setText("Introduzca su contraseña actual");
        lblOldPassword.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        add(lblOldPassword, gridBagConstraints);

        textNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNewPasswordActionPerformed(evt);
            }
        });
        textNewPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPasswordFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 20);
        add(textNewPassword, gridBagConstraints);

        textRenewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRenewPasswordActionPerformed(evt);
            }
        });
        textRenewPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPasswordFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 20);
        add(textRenewPassword, gridBagConstraints);

        textOldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textOldPasswordActionPerformed(evt);
            }
        });
        textOldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPasswordFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 20);
        add(textOldPassword, gridBagConstraints);

        buttonOk.setText("Cambiar");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(buttonOk, gridBagConstraints);

        buttonCancel.setText("Cancelar");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(buttonCancel, gridBagConstraints);

        lblMessage.setForeground(new java.awt.Color(204, 0, 51));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 5);
        add(lblMessage, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        controller.changePassword();
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        controller.cancel();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void textNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNewPasswordActionPerformed
        textRenewPassword.requestFocus();
    }//GEN-LAST:event_textNewPasswordActionPerformed

    private void textRenewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRenewPasswordActionPerformed
        textOldPassword.requestFocus();
    }//GEN-LAST:event_textRenewPasswordActionPerformed

    private void textOldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textOldPasswordActionPerformed
        buttonOkActionPerformed(evt);
    }//GEN-LAST:event_textOldPasswordActionPerformed

    private void textPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPasswordFocusGained
        JPasswordField text=(JPasswordField)evt.getSource();
        text.setText("");
        clearMessage();
    }//GEN-LAST:event_textPasswordFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblOldPassword;
    private javax.swing.JLabel lblRenewPassword;
    private javax.swing.JPasswordField textNewPassword;
    private javax.swing.JPasswordField textOldPassword;
    private javax.swing.JPasswordField textRenewPassword;
    // End of variables declaration//GEN-END:variables
}
